title: Nigella
email: your-email@example.com
description: StreetSeedsBulgaria
destination: docs
baseurl: "/nigella-site"
url: ""
facebook_page: https://www.facebook.com/streetseedsbulgaria/
business_site: https://streetseedsbulgaria.business.site/

# Build settings

plugins:
  - jekyll-feed


exclude:
  - docs
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
